name: Terraform Deploy

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}

          - name: Write GitHub App Private Key
            run: |
              echo "${{ secrets.APP_PEM }}" > github_app.pem
              chmod 600 github_app.pem
              echo "PEM file written successfully"
              ls -la github_app.pem

          - name: Terraform Init
            env:
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
              TF_VAR_app_id: ${{ secrets.APP_ID }}
              TF_VAR_app_installation_id: ${{ secrets.INSTALLATION_ID }}
              TF_VAR_app_pem_file: github_app.pem
            run: terraform init

          - name: Terraform Apply
            env:
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
              TF_VAR_app_id: ${{ secrets.APP_ID }}
              TF_VAR_app_installation_id: ${{ secrets.INSTALLATION_ID }}
              TF_VAR_app_pem_file: github_app.pem
            run: terraform apply -auto-approve
