name: Terraform Deploy

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2

          - name: Write Github App Private Key
            run: |
              echo "${{ secrets.APP_PEM }}" > github_app.pem
              chmod 600 github_app.pem

          - name: Install Python dependencies
            run: |
              python -m pip install --upgrade pip
              pip install PyJWT cryptography requests

          - name: Get installation ID
            id: get_installation_id
            env:
              GITHUB_APP_ID: ${{ secrets.APP_ID }}
              GITHUB_APP_PRIVATE_KEY: ${{ secrets.APP_PEM }}
              GITHUB_ORGANIZATION: ${{ secrets.ORGANIZATION }}
            run: |
              installation_id=$(python3 get_installation_id.py)
              echo "installation_id=$installation_id"
              echo "GITHUB_INSTALLATION_ID=$installation_id" >> $GITHUB_OUTPUT

          - name: Terraform Init
            run: terraform init

          - name: Terraform Apply
            env:
              GITHUB_APP_ID: ${{ secrets.APP_ID }}
              GITHUB_INSTALLATION_ID: ${{ steps.get_installation_id.outputs.GITHUB_INSTALLATION_ID }}
              GITHUB_APP_PEM_FILE: github_app.pem
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
            run: terraform apply -auto-approve

