name: Terraform Deploy

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
              GITHUB_APP_ID: ${{ secrets.APP_ID }}
              GITHUB_APP_INSTALLATION_ID: ${{ secrets.INSTALLATION_ID }}
              GITHUB_APP_PEM_FILE: ${{ secrets.APP_PEM }}
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}

          - name: Terraform Init
            run: terraform init

          - name: Terraform Apply
            run: terraform apply -auto-approve
