name: Terraform Deploy

on:
    push:
        branches:
        - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
              terraform_version: "1.12.2"

          - name: Terraform Init
            run: terraform init

          - name: Terraform Plan
            env:
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
              TF_VAR_app_id: ${{ secrets.APP_ID }}
              TF_VAR_app_installation_id: ${{ secrets.INSTALLATION_ID }}
              TF_VAR_app_pem_file: ${{ secrets.APP_PEM }}
            run: terraform plan -out=tfplan

          - name: Terraform Apply
            if: github.ref == 'refs/heads/main'   # only apply on main branch (optional safety)
            env:
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
              TF_VAR_app_id: ${{ secrets.APP_ID }}
              TF_VAR_app_installation_id: ${{ secrets.INSTALLATION_ID }}
              TF_VAR_app_pem_file: ${{ secrets.APP_PEM }}
            run: terraform apply -auto-approve tfplan
