name: Terraform Deploy

on:
    push:
        branches:
        - main

permissions:
    contents: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Python
            uses: actions/setup-python@v5
            with:
              python-version: "3.11"

          - name: Install Python deps
            run: pip install google-api-python-client google-auth google-auth-httplib2 requests

          - name : Fetch Google Sheet -> snapshot.json
            env:
              GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
              SHEET_ID: ${{ secrets.SHEET_ID }}
              TAB_REPOS_GID: ${{ secrets.TAB_REPOS_GID }}
              TAB_MEMBERS_GID: ${{ secrets.TAB_MEMBERS_GID }}
              TAB_TEAMS_GID: ${{ secrets.TAB_TEAMS_GID }}
              TAB_TEAM_MEMBERS_GID: ${{ secrets.TAB_TEAM_MEMBERS_GID }}
              TAB_BRANCHES_GID: ${{ secrets.TAB_BRANCHES_GID }}
              TAB_USER_PERMISSIONS_GID: ${{ secrets.TAB_USER_PERMISSIONS_GID }}
              TAB_TEAM_PERMISSIONS_GID: ${{ secrets.TAB_TEAM_PERMISSIONS_GID }}
              TAB_ADMINS_GID: ${{ secrets.TAB_ADMINS_GID }}
              TAB_CODEOWNERS_GID: ${{ secrets.TAB_CODEOWNERS_GID }}
              OUTPUT_PATH: data/snapshot.json
            run: python scripts/sheet_to_snapshot.py


          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v2
            with:
              cli_config_credentials_token: ${{ secrets.TFC_TOKEN }}
              terraform_version: "1.12.2"

          - name: Terraform Init
            run: terraform init

          - name: Terraform Plan
            env:
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
              TF_VAR_app_id: ${{ secrets.APP_ID }}
              TF_VAR_app_installation_id: ${{ secrets.INSTALLATION_ID }}
              TF_VAR_app_pem_file: ${{ secrets.APP_PEM }}
              TF_VAR_config_path: data/snapshot.json  
            run: terraform plan -out=tfplan

          - name: Terraform Apply
            if: github.ref == 'refs/heads/main'   # only apply on main branch (optional safety)
            env:
              TF_VAR_github_organization: ${{ secrets.ORGANIZATION }}
              TF_VAR_app_id: ${{ secrets.APP_ID }}
              TF_VAR_app_installation_id: ${{ secrets.INSTALLATION_ID }}
              TF_VAR_app_pem_file: ${{ secrets.APP_PEM }}
            run: terraform apply -auto-approve tfplan
